language: python
sudo: false

addons:
  postgresql: "9.4"
  apt:
    packages:
    - libyaml-dev
    - python-dev
    - python-setuptools
    - libevent-dev

python:
  - "2.7"

env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  apt: true
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

install:
  - easy_install -U pip
  - pip install -U -r requirements.txt

script:
  - python -m runtest
  - pylint --rcfile=.pylintrc data_bucket maintenance

notifications:
  slack: collectrium:flckGVOJPRClghuu4hyiEANe
