language: python
sudo: false

python:
  - "2.7"

env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  apt: true
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

install:
    - easy_install -U tox==2.3.1

script:
    - tox

